<<<<<<< HEAD
# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - teaching.md
  - talks.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: dark # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
=======
theme: jekyll-theme-slate
>>>>>>> 759ab6453bda9d1d7e4286ef691477be0e85f23c
